export const ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  dashboardManager: '/dashboard/manager',
  dashboardEmployee: '/dashboard/employee',
  inventory: '/inventory',
  inventoryAdd: '/inventory/add',
  inventoryEdit: '/inventory/edit/:id',
  inventoryRestock: '/inventory/restock',
  inventorySpoilage: '/inventory/spoilage',
  inventoryCount: '/inventory/count',
  inventoryHistory: '/inventory/history',
  inventorySuppliers: '/inventory/suppliers',
  reportsSales: '/reports/sales',
  reportsInventory: '/reports/inventory',
  reportsPayments: '/reports/payments',
  reportsSuppliers: '/reports/suppliers',
  purchaseOrders: '/purchasing/orders',
  receiving: '/purchasing/receiving',
  manageUsers: '/manage/users',
  manageRoles: '/manage/roles',
  manageDiscounts: '/manage/discounts',
  managePromotions: '/manage/promotions',
  manageBranches: '/manage/branches',
  manageDevices: '/manage/devices',
};
